### ISSUE TITLE
不支持mssql吗?

### ISSUE THREAD

**Issue by 107295472** [mikezss/skl-go#1]

**Comment by mikezss** [comment]
通过beego源码db_alias.go获知beego的orm框架支持以下数据库：
"mysql":    DRMySQL,
		"postgres": DRPostgres,
		"sqlite3":  DRSqlite,
		"tidb":     DRTiDB,
		"oracle":   DROracle,
		"oci8":     DROracle, // github.com/mattn/go-oci8
		"ora":      DROracle, //https://github.com/rana/ora
