### ISSUE TITLE
前端页面的问题？？

### ISSUE THREAD

**Issue by wzguo** [mikezss/skl-go#2]
是数据不对吗？我启动起来的效果是样的。使用的是MySQL数据库。
![snipaste_20190301_160857](https://user-images.githubusercontent.com/8574644/53624862-9199f080-3c3c-11e9-9b6b-692c07263996.jpg)

**Comment by mikezss** [comment]
mysql.sql更新。cmn_modual_tb表追加了displayno排序字段，所以初始化的sql文也需要追加该字段。

**Comment by wzguo** [comment]
@mikezss 我更新了数据库，页面展示还是一样的，正常是什么样子的？

**Comment by mikezss** [comment]
请确认cmn_modual_tb表中是否有初始化数据。如果没有，请删除该表，重新启动main.exe。
或者手工导入mysql.sql文件中和cmn_modual_tb有关的sql文。
